def raise_exception():
    return "a" + 2